name: wangkie_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^15.1.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  iconsax: ^0.0.8
  another_flushbar: ^1.12.30
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  firebase_core: ^3.13.0
  animated_toggle_switch: ^0.8.5
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  # flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.11
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
