// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvA9Q9j4dtZJPmxqnPNlF1Y8QEQmPHlEw',
    appId: '1:653060573487:android:31bc78965fed7f46fe79da',
    messagingSenderId: '653060573487',
    projectId: 'wangkie-86eb3',
    storageBucket: 'wangkie-86eb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeoz8ob2H9mf_zKst8X_AvlZEc9eAwjXk',
    appId: '1:653060573487:ios:71c7cf55b03f0633fe79da',
    messagingSenderId: '653060573487',
    projectId: 'wangkie-86eb3',
    storageBucket: 'wangkie-86eb3.firebasestorage.app',
    androidClientId: '653060573487-nqn4kqajk70k5a6dil060du80l4q77ce.apps.googleusercontent.com',
    iosClientId: '653060573487-7et5280juv2jo05ebfehmdqbded85ccp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wangkieApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6jDhR5ZHywTnXihRZFAnF8IC9h5Rx78',
    appId: '1:653060573487:web:0da0a1ce0a8b8f15fe79da',
    messagingSenderId: '653060573487',
    projectId: 'wangkie-86eb3',
    authDomain: 'wangkie-86eb3.firebaseapp.com',
    storageBucket: 'wangkie-86eb3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr6jDhR5ZHywTnXihRZFAnF8IC9h5Rx78',
    appId: '1:653060573487:web:6b62ad110bfb62a4fe79da',
    messagingSenderId: '653060573487',
    projectId: 'wangkie-86eb3',
    authDomain: 'wangkie-86eb3.firebaseapp.com',
    storageBucket: 'wangkie-86eb3.firebasestorage.app',
  );

}